server:
  port: 8081

spring:
  application:
    name: user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
        group: mdx
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
  feign:
    sentinel:
      enabled: true
  redis:
    database: 7
    host: devellabookredis.redis.rds.aliyuncs.com
    password: Hzsunflowers13579
    port: 6379
    timeout: 2000

elasticsearch:
  host: 118.31.171.207:9200
  port: 9200
  scheme: http


#==============================Sa-Token配置==============================
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 86400
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: random-128
  # 是否输出操作日志
  is-log: false


